stages:
  - test

python3.5:
  type: test
  stage: test
  image: python3.5
  before_script:
    - pip install -r requirements.txt
  script:
   - nosetests --with-coverage --cover-package=

python3.6:
  type: test
  stage: test
  image: python3.6
  before_script:
    - pip install -r requirements.txt
  script:
   - nosetests --with-coverage --cover-package=pyOutlook