stages:
  - tests
  - deploy

python2.7:
  type: test
  stage: tests
  image: python:2.7
  before_script:
    - pip install -r dev_requirements.txt
  script:
   - nosetests --with-coverage --cover-package=pyOutlook

python3.5:
  type: test
  stage: tests
  image: python:3.5
  before_script:
    - pip install -r dev_requirements.txt
  script:
   - nosetests --with-coverage --cover-package=pyOutlook

python3.6:
  type: test
  stage: tests
  image: python:3.6
  before_script:
    - pip install -r dev_requirements.txt
  script:
   - nosetests --with-coverage --cover-package=pyOutlook

package:
  stage: deploy
  image: python:3.7
  script:
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - twine upload --username="$PYPI_USERNAME" --password="$PYPI_PASSWORD" dist/*
  environment:
    name: pypi
  only:
    - tags
