import requests

from pyOutlook.internal.utils import check_response

__all__ = ['Folder']


class Folder(object):
    """Represents a mail folder in an Outlook account.

    Provides methods for managing folders and retrieving messages within them.

    :param account: The OutlookAccount this folder belongs to.
    :type account: OutlookAccount
    :param folder_id: The static ID generated by Outlook to identify this folder.
    :type folder_id: str
    :param folder_name: The display name of this folder.
    :type folder_name: str
    :param parent_id: The ID of the parent folder.
    :type parent_id: str
    :param child_folder_count: The number of child folders inside this folder.
    :type child_folder_count: int
    :param unread_count: The number of unread messages inside this folder.
    :type unread_count: int
    :param total_items: Total count of all items inside this folder.
    :type total_items: int

    :ivar account: The associated OutlookAccount.
    :ivar id: The folder's unique identifier.
    :ivar name: The display name of the folder.
    :ivar parent_id: The parent folder's ID.
    :ivar child_folder_count: Number of child folders.
    :ivar unread_count: Count of unread messages.
    :ivar total_items: Total items in folder.

    Example::

        # Get all folders
        folders = account.folders.all()
        for folder in folders:
            print(f'{folder.name}: {folder.unread_count} unread')

        # Work with a specific folder
        inbox = account.folders.get('Inbox')
        messages = inbox.messages()
    """

    def __init__(self, account, folder_id, folder_name, parent_id, child_folder_count, unread_count, total_items):
        self.account = account
        self.parent_id = parent_id
        self.child_folder_count = child_folder_count
        self.unread_count = unread_count
        self.total_items = total_items
        self.name = folder_name
        self.id = folder_id

    def __str__(self):
        return self.name

    def __repr__(self):
        return str(self)
        
    @property
    def headers(self) -> dict:
        """HTTP headers for API requests.

        :returns: Dictionary with Authorization and Content-Type headers.
        :rtype: dict
        """
        return {"Authorization": "Bearer " + self.account.access_token, "Content-Type": "application/json"}

    @classmethod
    def _json_to_folder(cls, account, json_value: dict) -> 'Folder':
        """Converts JSON to a Folder instance.

        .. deprecated::
            Use :meth:`FolderService._json_to_folder` directly instead.
            This method exists for backward compatibility.

        :param account: The OutlookAccount for the folder.
        :type account: OutlookAccount
        :param json_value: JSON object representing a folder.
        :type json_value: dict

        :returns: Folder instance.
        :rtype: Folder
        """
        from pyOutlook.services.folder import FolderService
        return FolderService._json_to_folder(account, json_value)

    @classmethod
    def _json_to_folders(cls, account, json_value: dict) -> list['Folder']:
        """Converts JSON array to list of Folder instances.

        .. deprecated::
            Use :meth:`FolderService._json_to_folders` directly instead.
            This method exists for backward compatibility.

        :param account: The OutlookAccount for the folders.
        :type account: OutlookAccount
        :param json_value: JSON response containing ``'value'`` array.
        :type json_value: dict

        :returns: List of Folder instances.
        :rtype: list[Folder]
        """
        from pyOutlook.services.folder import FolderService
        return FolderService._json_to_folders(account, json_value)

    def rename(self, new_folder_name: str) -> 'Folder':
        """Renames the folder to the provided name.

        :param new_folder_name: The new display name for the folder.
        :type new_folder_name: str

        :returns: A new Folder instance representing the renamed folder.
        :rtype: Folder

        :raises AuthError: If authentication fails (invalid or expired token).
        :raises RequestError: If the API request fails.
        """
        headers = self.headers
        endpoint = 'https://graph.microsoft.com/v1.0/me/MailFolders/' + self.id
        payload = '{ "DisplayName": "' + new_folder_name + '"}'

        r = requests.patch(endpoint, headers=headers, data=payload)

        if check_response(r):
            return_folder = r.json()
            return self._json_to_folder(self.account, return_folder)

    def get_subfolders(self) -> list['Folder']:
        """Retrieve all child folders inside this folder.

        :returns: List of child Folder instances.
        :rtype: list[Folder]

        :raises AuthError: If authentication fails (invalid or expired token).
        :raises RequestError: If the API request fails.
        """
        headers = self.headers
        endpoint = 'https://graph.microsoft.com/v1.0/me/MailFolders/' + self.id + '/childfolders'

        r = requests.get(endpoint, headers=headers)

        if check_response(r):
            return self._json_to_folders(self.account, r.json())

    def delete(self) -> None:
        """Deletes this folder.

        Permanently removes the folder and its contents from the mailbox.

        :raises AuthError: If authentication fails (invalid or expired token).
        :raises RequestError: If the API request fails.
        """
        headers = self.headers
        endpoint = 'https://graph.microsoft.com/v1.0/me/MailFolders/' + self.id

        r = requests.delete(endpoint, headers=headers)

        check_response(r)

    def move_into(self, destination_folder: 'Folder') -> 'Folder':
        """Move this folder into a different folder.

        This makes the current folder a child of the destination folder.

        :param destination_folder: The folder that should become the parent.
        :type destination_folder: Folder

        :returns: A new Folder instance representing this folder in its new location.
        :rtype: Folder

        :raises AuthError: If authentication fails (invalid or expired token).
        :raises RequestError: If the API request fails.
        """
        headers = self.headers
        endpoint = 'https://graph.microsoft.com/v1.0/me/MailFolders/' + self.id + '/move'
        payload = '{ "DestinationId": "' + destination_folder.id + '"}'

        r = requests.post(endpoint, headers=headers, data=payload, timeout=10)

        if check_response(r):
            return_folder = r.json()
            return self._json_to_folder(self.account, return_folder)

    def copy_into(self, destination_folder: 'Folder') -> 'Folder':
        """Copy this folder into the destination folder.

        Creates a copy of this folder as a child of the destination folder.

        :param destination_folder: The folder that should contain the copy.
        :type destination_folder: Folder

        :returns: A new Folder instance representing the copied folder.
        :rtype: Folder

        :raises AuthError: If authentication fails (invalid or expired token).
        :raises RequestError: If the API request fails.
        """
        headers = self.headers
        endpoint = 'https://graph.microsoft.com/v1.0/me/MailFolders/' + self.id + '/copy'
        payload = '{ "DestinationId": "' + destination_folder.id + '"}'

        r = requests.post(endpoint, headers=headers, data=payload, timeout=10)

        if check_response(r):
            return_folder = r.json()
            return self._json_to_folder(self.account, return_folder)

    def create_child_folder(self, folder_name: str) -> 'Folder':
        """Create a child folder within this folder.

        :param folder_name: The display name for the new folder.
        :type folder_name: str

        :returns: The newly created Folder instance.
        :rtype: Folder

        :raises AuthError: If authentication fails (invalid or expired token).
        :raises RequestError: If the API request fails.
        """
        headers = self.headers
        endpoint = 'https://graph.microsoft.com/v1.0/me/MailFolders/' + self.id + '/childfolders'
        payload = '{ "DisplayName": "' + folder_name + '"}'

        r = requests.post(endpoint, headers=headers, data=payload, timeout=10)

        if check_response(r):
            return_folder = r.json()
            return self._json_to_folder(self.account, return_folder)

    def messages(self) -> list:
        """Retrieve messages in this folder.

        Returns the default page of messages from this folder.

        :returns: List of Message instances.
        :rtype: list[Message]

        :raises AuthError: If authentication fails (invalid or expired token).
        :raises RequestError: If the API request fails.
        """
        from pyOutlook.services.message import MessageService

        headers = self.headers
        r = requests.get(f'https://graph.microsoft.com/v1.0/me/MailFolders/{self.id}/messages',headers=headers, timeout=10)
        check_response(r)
        return MessageService._json_to_messages(self.account, r.json())


